### ISSUE TITLE
Arrêt du jeu. Pas de patch français

### ISSUE THREAD

**Issue by Rekt4lover** [FSN-TRAD/FSN-FR#1]
Bonjour,

Voici le rapport d'une erreur concernant la partie  "3rd Day: Intermission Worms from hell", où le jeu crash pendant un dialogue. La version français n'est pas disponible également sur cette partie (toutes les parties en dehors du Fate/Stay night), je ne sais pas si c'est normal.

Bonne journée et bon courage, c'est vraiment top ce que vous faites ^^ !
[exception.zip](https://github.com/FSN-TRAD/FSN-FR/files/9283429/exception.zip)

**Comment by requinDr** [comment]
Bonjour,

J'ai regardé ton log, et l'erreur survient sur un script auquel tu n'as accès que lorsque tu as débloqué la route Heaven's feel.
Nous n'avons publié que la route Fate, donc le reste n'est pas en français et c'est normal.

Peut-être as-tu téléchargé une version avec une sauvegarde complète ou ne savais pas pour l'avancée de la traduction.
Quoi qu'il en soit, ce crash sera fixé lorsque nous sortirons Heaven's Feel, mais ce ne sera pas avant longtemps, nous devons finir de relire Unlimited Blade Works avant.

Bonne journée à toi aussi et merci !

**Comment by Rekt4lover** [comment]
Bonjour,

Merci beaucoup pour cette réponse. En effet, j'avais fait des recherches après et j'au vu que tout le travail été sur Unlimited Blade Works, j'aurais du le faire avant je tiens à m'en excuser.

Ok pour le problème, ce n'est pas un souci en soit, je ne savais pas si vous étiez au courant c'est pour ça que j'ai remonté l'information.

Merci encore et vraiment merci pour le boulot fait sur ce jeu, l'avoir en français rend quand même l'immersion beaucoup plus présente et c'est très appréciable !

Très beau travail, continuez comme ça c'est vraiment génial ! Bon courage et bonne journée !
